Update CI/workflow runners to Ubuntu 24.04
heroku/heroku-buildpack-php pull request #745
Opened 2024-07-12 15:02 UTC by dzuelke

See also:
https://github.com/actions/runner-images/issues/9848 https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZRd13d2ce2d455470495cbd34cf

2024-07-12 16:05 UTC, edmorley commented on .github/workflows/platform-build.yml
> +    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
> But we could always add `-small` just for ARM.

I've requested it here:
https://salesforce-internal.slack.com/archives/C05BDUMJWRK/p1720800090471269?thread_ts=1719950353.496499&cid=C05BDUMJWRK

2024-07-12 16:13 UTC, dzuelke commented on .github/workflows/platform-build.yml
> +    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
Yes, I used `-ip` due to the absence of `-small`, because I want to be "economical" with the runner sizes.

2024-07-12 16:15 UTC, edmorley commented on .github/workflows/platform-build.yml
> +    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
`-small` now exists as of the last few mins :-)

2024-07-15 13:26 UTC, edmorley requested changes

2024-07-15 13:26 UTC, edmorley commented on .github/workflows/platform-build.yml
> +    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
```suggestion
    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-small' || 'ubuntu-24.04' }}
```

2024-07-15 13:26 UTC, edmorley commented on .github/workflows/platform-remove.yml
> +    runs-on: ${{ endsWith(inputs.stack, 'arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
```suggestion
    runs-on: ${{ endsWith(inputs.stack, 'arm64') && 'pub-hk-ubuntu-24.04-arm-small' || 'ubuntu-24.04' }}
```

2024-07-15 13:26 UTC, edmorley commented on .github/workflows/platform-sync.yml
> +    runs-on: ${{ endsWith(matrix.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
```suggestion
    runs-on: ${{ endsWith(matrix.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-small' || 'ubuntu-24.04' }}
```

2024-07-15 13:26 UTC, edmorley commented on .github/workflows/platform-sync.yml
> +    runs-on: ${{ endsWith(matrix.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
```suggestion
    runs-on: ${{ endsWith(matrix.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-small' || 'ubuntu-24.04' }}
```

2024-07-15 13:26 UTC, edmorley commented on .github/workflows/platform-build.yml
> +    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-ip' || 'ubuntu-24.04' }}
```suggestion
    runs-on: ${{ endsWith(inputs.stack, '-arm64') && 'pub-hk-ubuntu-24.04-arm-small' || 'ubuntu-24.04' }}
```

2024-07-15 14:34 UTC, edmorley approved these changes

2024-07-15 14:34 UTC, merged

2024-07-15 20:56 UTC, edmorley commented
@dzuelke These docs need updating too:
https://github.com/heroku/languages-team/blob/39a7c7ad29410b701f3113fb0d40f85110bc7d0e/languages/php/platform.md?plain=1#L179